### ISSUE TITLE
Test version 2.0.0-rc1

### ISSUE THREAD

**Issue by ccztux** [ccztux/glsysbackup#82]

**Comment by ccztux** [comment]
Tasklist for extensive testing:
- [ ] Add a notification command to report the backup job status (#4)
- [ ] Multiple pre- and post-backup-scripts (#123)
- [ ] Add example post- and pre-backup scripts (#121)
